[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",

  # All this nonsense is here to ensure that portable-atomic builds against the
  # esp32c3 variant which technically doesn't have atomics. But its single core
  # so its fine.

  # Enable atomic codegen for RISCV target
  "-C", "target-feature=+a",
  # For this specific triple, make sure rust builds in a way where it will allow
  # atomics even though its not technically allowed in the target triple.
  "--cfg", "target_has_atomic_load_store",
  "--cfg", 'target_has_atomic_load_store="8"',
  "--cfg", 'target_has_atomic_load_store="16"',
  "--cfg", 'target_has_atomic_load_store="32"',
  "--cfg", 'target_has_atomic_load_store="ptr"',
  # Same for compare and swaps
  "--cfg", "target_has_atomic",
  "--cfg", 'target_has_atomic="8"',
  "--cfg", 'target_has_atomic="16"',
  "--cfg", 'target_has_atomic="32"',
  "--cfg", 'target_has_atomic="ptr"',
  # Yap at portable-atomic that this target has atomic support so the dam thing
  # builds a binary.
  "--cfg", "portable_atomic_unsafe_assume_single_core",
]
target = "riscv32imc-unknown-none-elf"
